# Generated by Django 5.0.14 on 2025-10-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="writingtemplate",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
